GET http://localhost:3001/info/

###
GET http://localhost:3001/api/persons/65cbc0de2038ac999ea7e7dd

###
DELETE  http://localhost:3001/api/persons/65cbc0de2038ac999ea7e7dd

###
PUT http://localhost:3001/api/persons/65cbc0de2038ac999ea7e7dd
Content-Type: application/json

{
  "name": "Adrian",
  "number": 1234
}